language: python
group: deprecated-2017Q4
sudo: required
services:
  - memcached
  - postgresql
  - redis-server
python:
  - '2.7'
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
addons:
  chrome: stable
env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    - TRAVIS_NODE_VERSION=8.9.1
    - YARN_VERSION="1.3.2"
install:
  - 'export PATH=$PATH:~/.bin'
  - rvm install 2.2.5
  - rvm use 2.2.5
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g "yarn@${YARN_VERSION}"
  - make install-tests
  - python -m pip install codecov
  - pip freeze
script:
  - make lint
  - py.test --cov . --cov-report="xml:.artifacts/coverage.xml" --junit-xml=".artifacts/junit.xml" --html="artifacts/pytest.html" || exit 1
after_success:
  - codecov -e TEST_SUITE
after_failure:
  - dmesg | tail -n 100
after_script:
  - npm install -g @zeus-ci/cli
  - zeus upload -t "text/xml+xunit" .artifacts/*junit.xml
  - zeus upload -t "text/xml+coverage" .artifacts/*coverage.xml
  - zeus upload -t "text/xml+coverage" .artifacts/coverage/cobertura-coverage.xml
  - zeus upload -t "text/html+pytest" .artifacts/*pytest.html
  - zeus upload -t "text/plain+pycodestyle" .artifacts/*pycodestyle.log
  - zeus upload -t "text/xml+checkstyle" .artifacts/*checkstyle.xml
  - zeus upload -t "application/webpack-stats+json" .artifacts/*webpack-stats.json
notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/3b18261a-deb8-11e7-867b-0a580a281404/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
