sudo: false
language: python
services:
- memcached
- postgresql
- redis-server
python:
- '2.7'
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/pip/wheels
  - $HOME/virtualenv/python2.7/src
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
  - PIP_DISABLE_PIP_VERSION_CHECK=on
  - SENTRY_SKIP_BACKEND_VALIDATION=1
  - CXX=g++-4.8
  - TRAVIS_NODE_VERSION=4
install:
# we want to test against sentry master
- rvm install 2.2.5
- rvm use 2.2.5
- nvm install $TRAVIS_NODE_VERSION
- bundle install
- make install-tests
- python -m pip install codecov
- pip freeze
script:
- bundle exec danger
- make lint
- coverage run --source=src -m py.test
after_success:
- codecov -e TEST_SUITE
